SQL> CREATE USER a IDENTIFIED BY a;

SQL> GRANT CREATE SESSION, CREATE TABLE TO a;

SQL> GRANT SELECT ANY TABLE TO a;

SQL> CREATE USER b IDENTIFIED BY b;

SQL> GRANT CREATE SESSION,CREATE TABLE TO b;

SQL> GRANT SELECT ANY TABLE TO b;

SQL> grant all privileges to a;

SQL> grant all privileges to b;
